from fpdf import FPDF
import os

pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=12)

# Header
pdf.set_font("Arial", 'B', 16)
pdf.cell(200, 10, txt="MAPA-RD INTEL :: OSINT REPORT", ln=1, align='C')
pdf.ln(10)

# Metadata
pdf.set_font("Arial", size=10)
pdf.cell(200, 10, txt="CLASSIFICATION: CONFIDENTIAL / NOFORN", ln=1)
pdf.cell(200, 10, txt="DATE: 2026-02-12", ln=1)
pdf.cell(200, 10, txt="TARGET: SIMULATION RECORD (DEMO)", ln=1)
pdf.ln(10)

# Content
pdf.set_font("Arial", size=12)
pdf.multi_cell(0, 10, txt="This report was generated by the MAPA-RD Intelligence Platform (PHP Engine).\n\n"
                      "SCAN SUMMARY:\n"
                      "- Protocol: Passive Reconnaissance\n"
                      "- Modules: DNS, Breaches, Dark Web\n"
                      "- Risk Level: HIGH\n\n"
                      "FINDINGS:\n"
                      "[!] 3 Potential Credential Leaks detected in public databases.\n"
                      "[!] Domain expiration impending (2027).\n"
                      "[!] Email metadata correlates with 2 social profiles.\n\n"
                      "RECOMMENDATION:\n"
                      "Immediate review of password policies required. Enable 2FA on all identified accounts.\n\n"
                      "*** END OF REPORT ***")

output_dir = "api/reports"
os.makedirs(output_dir, exist_ok=True)
pdf.output(os.path.join(output_dir, "mock.pdf"))

print("PDF Generated Successfully at api/reports/mock.pdf")
